name: build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.10', '1.11', '1.12' ]
    env:
      TEST_RESULTS: /tmp/test-results
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go env
      - run: mkdir -pv $TEST_RESULTS
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 0.6.0
      - run: gotestsum --junitfile ${TEST_RESULTS}/unit-tests.xml -- -timeout 5m -p 1 ./...
